### PR TITLE
Added Linux deployment script

### PR DESCRIPTION
**Pull request by Nihlus**
I've gone ahead and added a small Linux deployment script. It does everything the Windows script does with some additional error checking, and has been tested on my Linux Mint install.

### CODE REVIEW

**Comment by MHeironimus** [comment]
@Nihlus Thank you for your Pull Request. It will try to test it out in the next few weeks or so.

Quick question, I do not have a lot of experience with Linux scripts (so this may be a dumb question), but could the following lines:

~~~
cp "Joystick/"* "$INSTALLPATH" 
cp "Joystick/src"* "$INSTALLPATH" 
cp -r "Joystick/examples" "$INSTALLPATH" 
~~~

have been replaced by the following line?

~~~
cp -r "Joystick/"* "$INSTALLPATH" 
~~~

**Comment by Nihlus** [comment]
No, cp works a little differently than xcopy. What you've got in the batch file will not preserve the directory structure, while cp will - that's all well and good for Arduino, since it expects a flat directory structure for libraries, but that's no bueno for cp. Were I to simply use 

`cp -r "Joystick/"* "$INSTALLPATH" `

the source files (which Arduino wants at the top level folder "Joystick") would end up in "Joystick/src" instead. The inverse is true for "examples", which we do want in a subfolder, which is why I've omitted the asterisk and instead am copying the whole directory.

**Comment by Nihlus** [comment]
Ah, that's strange. The library would not load unless the source files were
outside the src folder when I tested it.

**Comment by MHeironimus** [comment]
@Nihlus I finally had some time today to get a Linux environment up and running (specifically RASPBIAN JESSIE WITH PIXEL - Version January 2017). 

I grabbed a copy of your Linux deployment script, made a few modifications, and pushed it back up to a new `linux-deploy` branch on my Fork (i.e. https://github.com/MHeironimus/ArduinoJoystickLibrary/tree/linux-deploy). Would you be able to pull down this branch and see if it works for you on your Linux machine?

Thanks,
Matt

**Comment by MHeironimus** [comment]
@Nihlus - Thank you for your submission. I incorporated your suggestions in a different pull request, so I am closing this one out. Let me know if you have any issues with the new version (i.e. Version 2.0.3).

Thanks again for your help with this.

**Comment by Nihlus** [comment]
Super :D

**Pull request closed without merging**
